python_library(
  name="lib",
  sources=rglobs("iceqube/**/*.py"),
  dependencies=[
    "3rdparty/python:SQLAlchemy",
    "3rdparty/python:futures",
  ],
    provides=setup_py(
    name="iceqube",
    version="0.0.5",
    description="",
    long_description="",
    author='Learning Equality',
    author_email='aron@learningequality.org',
    url='https://github.com/learningequality/iceqube',
    license='MIT',
    zip_safe=True,
    keywords=('queue', 'async'),
    classifiers=[
        'Development Status :: 2 - Pre-Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Natural Language :: English',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
    ]
  )
)
